Features
hernandanielzamora/Capstone-Project pull request #2
Opened 2023-03-13 19:47 UTC by hernandanielzamora

2023-03-14 22:38 UTC, mckent05 requested changes
Hi @hernandanielzamora, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You have made a good attempt on your first capstone in the program, keep going! 💪 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 22:38 UTC, mckent05 commented on pages/aboutme.html
> +            <a href="../index.html"><img src="../media/cogress-logo.png" alt="Congress Logo" class="navbar-logo"></a>
- Good job done so far, the navbar in the mobile version of your project is not styled as it is in the design template. Please make sure that the logo is not visible in the design template. Please fix this for both the home and about page 👍 👍 

Your project:
<img width="279" alt="gj34g" src="https://user-images.githubusercontent.com/73607512/225144437-cde1f3a6-ac15-4ca1-9189-486f05552249.PNG">

Design template:
<img width="283" alt="gQ3F" src="https://user-images.githubusercontent.com/73607512/225144630-59460865-1469-431d-a4d5-da8d96fd5c43.PNG">

- For the desktop version, please ensure that there are equal margins on the left and right sides of the bottom navbar.
- Also, please ensure that in the desktop version, the right-hand side of the links is aligned in the same position as that of the bottom navbar.
Your project:
<img width="966" alt="vwjnjw" src="https://user-images.githubusercontent.com/73607512/225146591-65d0b738-450c-42d8-b24a-588394cc6719.PNG">

Design template:
<img width="635" alt="whawgae" src="https://user-images.githubusercontent.com/73607512/225146972-df9f71be-c10e-4d97-86d7-818c2ebe712e.PNG">

2023-03-14 22:38 UTC, mckent05 commented on index.html
> +      </div>
- Good job done, but there are some differences between your design and the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
 Your project:
- The footer should have your logo aligned to the left and text aligned to the right, please fix this 🙏 
- The background should be a white background as it is in the design template

Your project:
<img width="949" alt="2gwefg" src="https://user-images.githubusercontent.com/73607512/225149756-f6095978-ff5e-4493-8e65-15856f2772e0.PNG">

Design template:
<img width="625" alt="4on44" src="https://user-images.githubusercontent.com/73607512/225149824-20c2f60e-7481-4459-a179-1b03c7a43cf5.PNG">

2023-03-14 22:38 UTC, mckent05 commented on pages/aboutme.html
> +
- Good job done, but there are some differences between your design and the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
Your project:
-- The footer should have your logo aligned to the left and text aligned to the right, please fix this 🙏

2023-03-14 22:38 UTC, mckent05 commented on index.html
> +      </div>
- Good job done so far, for both the mobile and desktop versions, please align this section to the left of the page as it is in the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
- Also please ensure that the font size and weight match the one in the design template 👍 👍 

Your project:
<img width="649" alt="wetweg" src="https://user-images.githubusercontent.com/73607512/225154148-dce23f71-35e0-4c3f-9c74-1ce258cad5e8.PNG">

Design template:
<img width="448" alt="ttt" src="https://user-images.githubusercontent.com/73607512/225154355-580d2228-e1ff-4c0b-b1a4-1c8814acc147.PNG">

2023-03-14 22:38 UTC, mckent05 commented on index.html
> +      </div>
- To help improve the semantics of your site, I suggest tat you wrap each `program-content` in an `article` tag. Please fix this 😄

2023-03-14 22:38 UTC, mckent05 commented on index.html
> +      </div>
- Please align this section in the middle of the screen as it is in the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
<img width="726" alt="3g3g" src="https://user-images.githubusercontent.com/73607512/225155313-1b4f42d2-6944-4b7a-9b0c-a4a49c9e1c6e.PNG">

2023-03-14 22:38 UTC, mckent05 commented on javascript/index.js
> +  </div>`;
- Good job rendering this section of your page dynamically, please ensure that for each speaker, there is an image aligned to the left and the text is aligned to the right. Please ensure that the text does not overflow under the image as shown in the screenshot below, please fix this for both mobile and desktop versions 👍 👍 

Your project:
<img width="469" alt="twergkr" src="https://user-images.githubusercontent.com/73607512/225155988-26850700-1af6-4a5d-abde-94ccfc023194.PNG">

Design template
<img width="263" alt="jvrv" src="https://user-images.githubusercontent.com/73607512/225156170-12b5da9d-6676-4044-b73e-a94a99c8ee4c.PNG">

2023-03-14 22:38 UTC, mckent05 commented on index.html
> +  </section>
- For this section, please fix the background color to the same color in the design template, also please make sure that all your images/logo are in a row of 5/6 columns as seen in the template, please fix this 🙏 

Your project:
<img width="950" alt="OLVKVV" src="https://user-images.githubusercontent.com/73607512/225156613-f9a8b2ca-ca4a-473c-a079-9a457bbc50d7.PNG">

Design template:
<img width="628" alt="2fg2" src="https://user-images.githubusercontent.com/73607512/225156631-0930ea51-c409-4253-8e9b-9538e3b05c7f.PNG">

2023-03-14 22:38 UTC, mckent05 commented on pages/aboutme.html
> +      <div class="program-bar"></div>
- You seem to have some missing sections as shown in the design template. Please note that though you are allowed to personalize the content of this project, you are required to stick to the design layout, color, margins, spacing etc. Sticking to this will give confidence in recruiters that you can replicate exact business requirements 😄 
- I suggest that you include the following sections in your project and style them accordingly 👍 

Logo section:
<img width="553" alt="ffef" src="https://user-images.githubusercontent.com/73607512/225157427-5e38deed-8323-47ff-a6de-6f65e4662ef7.PNG">

Past events/commits:
<img width="551" alt="jvjwvev" src="https://user-images.githubusercontent.com/73607512/225157469-944aa198-ebcc-4887-ab33-c21120198568.PNG">

2023-03-15 01:14 UTC, didierganthier approved these changes
Hi @hernandanielzamora ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Nice UI Design ✔️ 

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-03-15 01:17 UTC, merged